### ISSUE TITLE
error while running example

### ISSUE THREAD

**Issue by GekoCH** [unfoldedcircle/integration-node-library#28]
Hy 

I tried to run the example but I get this error:
```
/home/integration-node-library-main/index.js:171
  #getDriverUrl(url, port) {
               ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/integration-node-library-main/examples/simulated-light/light.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

Any ideas?

**Comment by zehnm** [comment]
Which example did you try, the `examples/simulated-light/light.js`?
What Node.js version are you using?

**Comment by GekoCH** [comment]
> Which example did you try, the `examples/simulated-light/light.js`?

Yes
> What Node.js version are you using?

8.5.1

**Comment by zehnm** [comment]
Your Node.js version is very old. Please update to version 16 or newer:
https://nodejs.org/en/download

**Comment by GekoCH** [comment]
ok thx a lot and what distro of linux do you recommend

**Comment by GekoCH** [comment]
ok thx a lot now it works, just need to figure out why "dbad" is not working while I use the "entity_type" "media_player"

**Comment by GekoCH** [comment]
ok thx a lot now it works, just need to figure out why "dbad" is not working while I use the "entity_type" "media_player"
