### ISSUE TITLE
updateEntityAttributes leads to an error

### ISSUE THREAD

**Issue by GekoCH** [unfoldedcircle/integration-node-library#30]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I use the minimum-required.js to control my media player.
However when I try to update an Entity Attribut I get an error.

Here is the code to update the entity:
`uc.configuredEntities.updateEntityAttributes(
  "my_evita",
  new Map([[uc.Entities.MediaPlayer.ATTRIBUTES.VOLUME, 24]])
);`

ERROR:
```
/root/integration-node-library/lib/entities/entities.js:102
      this.#storage[id].attributes[key] = value;
                                        

TypeError: Cannot set properties of null (setting 'volume')
    at /root/integration-node-library/lib/entities/entities.js:102:41
    at Map.forEach (<anonymous>)
    at Entities.updateEntityAttributes (/root/integration-node-library/lib/entities/entities.js:101:16)
    at IntegrationAPI.<anonymous> (/root/integration-node-library/examples/mediaplayer/player.js:421:24)
    at IntegrationAPI.emit (node:events:514:28)
    at #entityCommand (/root/integration-node-library/index.js:476:10)
    at #messageReceived (/root/integration-node-library/index.js:353:36)

```

I used this example. uc.on events do work great but changing the Attributes of the entity fails...
https://github.com/unfoldedcircle/integration-node-library/blob/e57cd028a52775abb29d9ed81512fff9b2600c59/examples/minimum-required.js

### How to Reproduce

see above

### Expected behavior

see above

**Comment by zehnm** [comment]
Moving to https://github.com/unfoldedcircle/integration-node-library

**Comment by zehnm** [comment]
I can't reproduce this, even if I create a media-player without volume control features:
```js
const mediaPlayerEntity = new uc.Entities.MediaPlayer(
  "test_mediaplayer",
  new Map([
    ["en", "Foobar MediaPlayer"]
  ]),
  [uc.Entities.MediaPlayer.FEATURES.ON_OFF, uc.Entities.MediaPlayer.FEATURES.DPAD,
    uc.Entities.MediaPlayer.FEATURES.HOME, uc.Entities.MediaPlayer.FEATURES.MENU,
    uc.Entities.MediaPlayer.FEATURES.CHANNEL_SWITCHER,
    uc.Entities.MediaPlayer.FEATURES.SELECT_SOURCE,
    uc.Entities.MediaPlayer.FEATURES.COLOR_BUTTONS,
    uc.Entities.MediaPlayer.FEATURES.PLAY_PAUSE],
  new Map([
    [uc.Entities.MediaPlayer.ATTRIBUTES.STATE, uc.Entities.MediaPlayer.STATES.OFF],
    [uc.Entities.MediaPlayer.ATTRIBUTES.SOURCE_LIST, ["Radio", "Streaming", "Favorite 1", "Favorite 2", "Favorite 3"]]
  ])
);
uc.availableEntities.addEntity(mediaPlayerEntity);

// ...

uc.on(uc.EVENTS.ENTITY_COMMAND, async (wsHandle, entityId, entityType, cmdId, params) => {
  uc.configuredEntities.updateEntityAttributes( "test_mediaplayer", new Map([[uc.Entities.MediaPlayer.ATTRIBUTES.VOLUME, 24]]) );
}
```

Please provide a test case.

**Comment by GekoCH** [comment]
thx for the reply
I just took the light,js example and modified it to my needs. 
```
"use strict";

// use package in production
// const uc = require("uc-integration-api");
const uc = require("../../index");
uc.init("player.json");

uc.on(uc.EVENTS.CONNECT, async () => {
  await uc.setDeviceState(uc.DEVICE_STATES.CONNECTED);
});

uc.on(uc.EVENTS.DISCONNECT, async () => {
  await uc.setDeviceState(uc.DEVICE_STATES.DISCONNECTED);
});

uc.on(uc.EVENTS.SUBSCRIBE_ENTITIES, async (entityIds) => {
  // the integration will configure entities and subscribe for entity update events
  // the UC library automatically adds the subscribed entities
  // from available to configured
  // you can act on this event if you need for your device handling
  entityIds.forEach((entityId) => {
    console.log(`Subscribed entity: ${entityId}`);
  });
});

uc.on(uc.EVENTS.UNSUBSCRIBE_ENTITIES, async (entityIds) => {
  // when the integration unsubscribed from certain entity updates,
  // the UC library automatically remove the unsubscribed entities
  // from configured
  // you can act on this event if you need for your device handling
  entityIds.forEach((entityId) => {
    console.log(`Unsubscribed entity: ${entityId}`);
  });
});


uc.on(uc.EVENTS.SETUP_DRIVER, async (wsHandle, setupData) => {
  console.log("Setting up driver. Setup data: " + JSON.stringify(setupData));
  // do any initial checks here
  // ...
  await new Promise((resolve) => setTimeout(resolve, 300));

  // all good: confirm request. This will start the setup flow
  await uc.acknowledgeCommand(wsHandle);
  console.log("Acknowledged driver setup");

  // implement interactive setup flow, this is just a simulated example
  // ...
  await new Promise((resolve) => setTimeout(resolve, 1000));

  console.log("Sending setup progress that we are still busy...");
  await uc.driverSetupProgress(wsHandle);

  await new Promise((resolve) => setTimeout(resolve, 1000));

  console.log("Requesting user confirmation to finish setup...");
  await uc.requestDriverSetupUserConfirmation(wsHandle, "Please click next to continue driver setup");
});
 


uc.on(uc.EVENTS.SETUP_DRIVER_USER_DATA, async (wsHandle, userData) => {
  console.log("Received user input for driver setup: " + JSON.stringify(userData));
  await uc.acknowledgeCommand(wsHandle);

  // implement interactive setup flow, this is just a simulated example
  // ...
  await new Promise((resolve) => setTimeout(resolve, 700));

  console.log("Driver setup completed!");
  await uc.driverSetupComplete(wsHandle);
});
 


uc.on(uc.EVENTS.SETUP_DRIVER_USER_CONFIRMATION, async (wsHandle) => {
  console.log("Received user confirmation for driver setup: sending OK");
  await uc.acknowledgeCommand(wsHandle);

  // implement interactive setup flow, this is just a simulated example
  // ...
  await new Promise((resolve) => setTimeout(resolve, 700));

  // console.log("Sending setup progress that we are still busy...");
  await uc.driverSetupProgress(wsHandle);

  await new Promise((resolve) => setTimeout(resolve, 700));

  await uc.requestDriverSetupUserInput(wsHandle, "Data required", [
    { field: { text: { value: "192.168.1.221" } }, id: "address", label: { en: "Hostname or IP address" } },
    // { field: { password: {} }, id: "token", label: { en: "Access token" } },
    { field: { number: { max: 65535, min: 1, value: 8080 } }, id: "port", label: { en: "Port" } }
    // { field: { checkbox: { value: false } }, id: "ssl", label: { en: "Use SSL" } }
  ]);
});


const entityEvita = new uc.Entities.MediaPlayer(
  "my_evita",
  "evita entity",
  [uc.Entities.MediaPlayer.FEATURES.NEXT,
  uc.Entities.MediaPlayer.FEATURES.MUTE,
  uc.Entities.MediaPlayer.FEATURES.MUTE_TOGGLE,
  uc.Entities.MediaPlayer.FEATURES.PREVIOUS,
  uc.Entities.MediaPlayer.FEATURES.VOLUME,
  uc.Entities.MediaPlayer.FEATURES.VOLUME_UP_DOWN,
  uc.Entities.MediaPlayer.FEATURES.CHANNEL_SWITCHER,
  uc.Entities.MediaPlayer.FEATURES.COLOR_BUTTONS,
  uc.Entities.MediaPlayer.FEATURES.SEEK,
  uc.Entities.MediaPlayer.FEATURES.TOGGLE,
  uc.Entities.MediaPlayer.FEATURES.DPAD,
  uc.Entities.MediaPlayer.FEATURES.ON_OFF,
  uc.Entities.MediaPlayer.FEATURES.PLAY_PAUSE,
  uc.Entities.MediaPlayer.FEATURES.REPEAT,
  uc.Entities.MediaPlayer.FEATURES.SHUFFLE,
  uc.Entities.MediaPlayer.FEATURES.MEDIA_DURATION,
  uc.Entities.MediaPlayer.FEATURES.MEDIA_POSITION,
  uc.Entities.MediaPlayer.FEATURES.MEDIA_TITLE,
  uc.Entities.MediaPlayer.FEATURES.MEDIA_ARTIST,
  uc.Entities.MediaPlayer.FEATURES.MEDIA_ALBUM,
  uc.Entities.MediaPlayer.FEATURES.MEDIA_IMAGE_URL
  ],
  new Map([
    [uc.Entities.MediaPlayer.ATTRIBUTES.STATE, uc.Entities.MediaPlayer.STATES.OFF],
    [uc.Entities.MediaPlayer.ATTRIBUTES.VOLUME, 10]
  ])
);
uc.availableEntities.addEntity(entityEvita);


uc.configuredEntities.updateEntityAttributes( "my_evita", new Map([[uc.Entities.MediaPlayer.ATTRIBUTES.VOLUME, 24]]) );


  
// when a command request arrives from the core, handle the command
// in this example we just update the entity, but in reality, you'd turn on the light with your integration
// and handle the events separately for updating the configured entities
uc.on(uc.EVENTS.ENTITY_COMMAND, async (wsHandle, entityId, entityType, cmdId, params) => {
	console.log("");
	
	// console.log(`ENTITY COMMAND: ${entityId} ${entityType} ${cmdId} ${JSON.stringify(params, null, 4)}`);	
	console.log(`ENTITY COMMAND: ${entityId} ${cmdId} ${entityType} ${params ? JSON.stringify(params) : ""}`);



  // you need to acknowledge if the command was successfully executed
  // we just say OK there, but you need to add logic if the command is
  // really successfully executed on the device
  await uc.acknowledgeCommand(wsHandle);

});

```

**Comment by zehnm** [comment]
This part doesn't make sense, calling `configuredEntities.updateEntityAttributes` right after `availableEntities.addEntity`:
```js
uc.availableEntities.addEntity(entityEvita);


uc.configuredEntities.updateEntityAttributes( "my_evita", new Map([[uc.Entities.MediaPlayer.ATTRIBUTES.VOLUME, 24]]) );
```

After defining available entities in the driver, they are available for Remote Two to be configured.
Only after they are selected as configured entities, they will be in `uc.configuredEntities`.

The `uc.configuredEntities.updateEntityAttributes` call belongs in the command callback function:
```js
uc.on(uc.EVENTS.ENTITY_COMMAND, async (wsHandle, entityId, entityType, cmdId, params) => {
 // ...
}
```

**Comment by GekoCH** [comment]
of course it makes no sense, I did this just for fast testing even if I put the part
`uc.configuredEntities.updateEntityAttributes( "my_evita", new Map([[uc.Entities.MediaPlayer.ATTRIBUTES.VOLUME, 24]]) );`
into 
```
uc.on(uc.EVENTS.ENTITY_COMMAND, async (wsHandle, entityId, entityType, cmdId, params) => {
 // ...
}
```
I still get the error

maybe I need to remove the entity complety from the remote and restart

**Comment by GekoCH** [comment]
Thank you for all the patience with me.
After removing the entity and re-adding it works now!
Didn't know that this was necessary.
Thx a lot!
